FROM ubuntu:16.04

ENV DEBIAN_FRONTEND=noninteractive
ENV CB_SSH_PUB_KEY=NA
ENV CB_LOGIN=NA

RUN apt-get update
RUN apt-get install -y sudo rsync
RUN apt-get install -y python2.7
RUN apt-get install -y openssh-server
RUN ln -s /usr/bin/python2.7 /usr/bin/python
RUN mkdir /var/run/sshd
RUN echo 'root:temp4now' | chpasswd
RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

RUN useradd -m -p "$1$1rCJhvTo$nIoKRh4zdGdnk0Dntsdnq/" -s /bin/bash ubuntu
RUN useradd -m -p "$1$1rCJhvTo$nIoKRh4zdGdnk0Dntsdnq/" -s /bin/bash fedora
RUN useradd -m -p "$1$1rCJhvTo$nIoKRh4zdGdnk0Dntsdnq/" -s /bin/bash cbuser

RUN echo "ubuntu  ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers
RUN echo "fedora  ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers
RUN echo "cbuser  ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers

RUN echo 'ubuntu:temp4now' | chpasswd
RUN echo 'fedora:temp4now' | chpasswd
RUN echo 'cbuser:temp4now' | chpasswd

RUN ssh-keygen -q -t rsa -N '' -f /root/.ssh/id_rsa
RUN touch /root/.ssh/authorized_keys
RUN chmod 644 /root/.ssh/authorized_keys

RUN mkdir -p /home/ubuntu/.ssh/
RUN ssh-keygen -q -t rsa -N '' -f /home/ubuntu/.ssh/id_rsa
RUN touch /home/ubuntu/.ssh/authorized_keys
RUN chmod 644 /home/ubuntu/.ssh/authorized_keys
RUN chown -R ubuntu:ubuntu /home/ubuntu/

RUN mkdir -p /home/fedora/.ssh/
RUN ssh-keygen -q -t rsa -N '' -f /home/fedora/.ssh/id_rsa
RUN touch /home/fedora/.ssh/authorized_keys
RUN chmod 644 /home/fedora/.ssh/authorized_keys
RUN chown -R fedora:fedora /home/fedora/

RUN mkdir -p /home/cbuser/.ssh/
RUN ssh-keygen -q -t rsa -N '' -f /home/cbuser/.ssh/id_rsa
RUN touch /home/cbuser/.ssh/authorized_keys
RUN chmod 644 /home/cbuser/.ssh/authorized_keys
RUN chown -R cbuser:cbuser /home/cbuser/

RUN mkdir -p /etc/my_init.d
ADD inject_pubkey_and_start_ssh.sh /etc/my_init.d/inject_pubkey_and_start_ssh.sh

CMD ["/etc/my_init.d/inject_pubkey_and_start_ssh.sh"]