FROM REPLACE_BASE_VANILLA_UBUNTU

USER root

ENV DEBIAN_FRONTEND=noninteractive
ENV CB_SSH_PUB_KEY=NA
ENV CB_LOGIN=NA

RUN apt-get update; \
apt-get install -y sudo rsync python2.7; \
apt-get update; \
apt-get install -y openssh-server; \
ln -sf /usr/bin/python2.7 /usr/bin/python; \
mkdir -p /var/run/sshd; \
mkdir -p /etc/my_init.d

RUN echo 'root:temp4now' | chpasswd

RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config; \
sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

RUN useradd -m -p "$1$1rCJhvTo$nIoKRh4zdGdnk0Dntsdnq/" -s /bin/bash ubuntu; \
useradd -m -p "$1$1rCJhvTo$nIoKRh4zdGdnk0Dntsdnq/" -s /bin/bash fedora; \
useradd -m -p "$1$1rCJhvTo$nIoKRh4zdGdnk0Dntsdnq/" -s /bin/bash REPLACE_USERNAME; \
echo "ubuntu  ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers; \
echo "fedora  ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers; \
echo "REPLACE_USERNAME  ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers

#RUN echo 'ubuntu:temp4now' | chpasswd
#RUN echo 'fedora:temp4now' | chpasswd
#RUN echo 'REPLACE_USERNAME:temp4now' | chpasswd

RUN ssh-keygen -q -t rsa -N '' -f /root/.ssh/id_rsa; \
touch /root/.ssh/authorized_keys; \
chmod 644 /root/.ssh/authorized_keys; \
mkdir -p /home/ubuntu/.ssh/; \
rsync -a /root/.ssh/ /home/ubuntu/.ssh/; \
chown -R ubuntu:ubuntu /home/ubuntu/; \
mkdir -p /home/fedora/.ssh/; \
rsync -a /root/.ssh/ /home/fedora/.ssh/; \
chown -R fedora:fedora /home/fedora/; \
mkdir -p /home/fedora/.ssh/; \
rsync -a /root/.ssh/ /home/REPLACE_USERNAME/.ssh/; \
chown -R REPLACE_USERNAME:REPLACE_USERNAME /home/REPLACE_USERNAME;

ADD inject_pubkey_and_start_ssh.sh /etc/my_init.d/inject_pubkey_and_start_ssh.sh

CMD ["/etc/my_init.d/inject_pubkey_and_start_ssh.sh"]
