FROM REPLACE_BASE_CENTOS

ENV DEBIAN_FRONTEND=noninteractive
ENV CB_SSH_PUB_KEY=NA
ENV CB_LOGIN=NA

RUN yum -y update; yum clean all

RUN ln -s /sbin/ifconfig /usr/local/bin/ifconfig
RUN ln -s /sbin/ip /usr/local/bin/ip

RUN yum install -y \
psmisc \
ntp \
ntpdate \
git \
wget \
gcc \
make \
emacs \
sshpass \
curl \
vim \
screen \
rsync \
ncftp \
lftp \
libffi-devel \
openssl-devel \
python-webob \
python-beaker \
python-libvirt \
nmap-ncat \
netcat-openbsd
RUN cp /bin/nc /usr/local/bin/netcat

RUN yum install -y \
nmap \
openvpn 
RUN ln -s /usr/sbin/openvpn /usr/local/bin/openvpn

RUN yum install -y epel-release
RUN yum install -y python-pip
RUN yum install -y \
ganglia \
ganglia-gmond.REPLACE_ARCH1
RUN ln -s /usr/sbin/gmond /usr/local/bin/gmond

#RUN yum install -y httpd
RUN yum install -y redis 
RUN sed -i "s/.*bind 127.0.0.1/bind 0.0.0.0/" /etc/redis.conf

RUN yum install -y \
python-devel \
python-setuptools \
python-prettytable

RUN pip install --upgrade \
prettytable \
python-daemon \
twisted \
redis \
pymongo

RUN yum install -y \
pssh

RUN pip install --upgrade \
docutils \
setuptools \
markup \
pyyaml

RUN rsync -az /root/.ssh/ /home/cbuser/.ssh/
RUN echo "StrictHostKeyChecking=no" > /home/cbuser/.ssh/config 
RUN echo "UserKnownHostsFile=/dev/null" >> /home/cbuser/.ssh/config 
RUN chmod 600 /home/cbuser/.ssh/config
RUN chown -R cbuser:cbuser /home/cbuser/

USER cbuser
WORKDIR /home/cbuser/
RUN GIT_TRACE=1; GIT_CURL_VERBOSE=1 git clone --verbose http://github.com/ibmcb/cbtool.git
RUN mkdir -p /home/cbuser/cbtool/3rd_party
WORKDIR /home/cbuser/cbtool/3rd_party
#RUN git clone https://github.com/ibmcb/monitor-core.git
#RUN git clone https://github.com/ibmcb/HTML.py.git
WORKDIR /home/cbuser/cbtool/3rd_party/HTML.py
#RUN sudo python setup.py install
WORKDIR /home/cbuser
USER root
RUN chown -R cbuser:cbuser /home/cbuser