FROM REPLACE_NULLWORKLOAD_UBUNTU

RUN apt-get update

RUN mkdir -p /home/cbuser/linpack/benchmarks/linpack
COPY l_lpk_p_11.3.0.004.tgz /home/cbuser/l_lpk_p_11.3.0.004.tgz
RUN cd /home/cbuser/; tar -xzf l_lpk_p_11.3.0.004.tgz; rm l_lpk_p_11.3.0.004.tgz