FROM REPLACE_NULLWORKLOAD_UBUNTU

# kernbuild-install-pm
RUN apt-get update
RUN apt-get install -y build-essential bison flex libelf-dev libssl-dev bc time
# kernbuild-install-pm

# kernbench-install-git
RUN mkdir /home/REPLACE_USERNAME/foo; chown -R REPLACE_USERNAME:REPLACE_USERNAME /home/REPLACE_USERNAME; cd /home/REPLACE_USERNAME/foo; git clone https://github.com/linux-test-project/ltp.git -b 20180118
RUN cd /home/REPLACE_USERNAME/foo; chmod +x ltp/utils/benchmark/kernbench-0.42/kernbench
RUN cd /home/REPLACE_USERNAME/foo; wget -N -v -P /home/REPLACE_USERNAME/foo https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.16.8.tar.xz; tar xf linux-4.16.8.tar.xz; mv linux-4.16.8 linux
# kernbench-install-git

RUN chown -R REPLACE_USERNAME:REPLACE_USERNAME /home/REPLACE_USERNAME
