FROM REPLACE_NULLWORKLOAD_CENTOS

RUN yum -y update; yum clean all

# java-install-man
RUN yum install -y java-1.7.0-openjdk
# java-install-man

# cassandra-install-man
#RUN wget -N -q -P /home/REPLACE_USERNAME http://rpm.datastax.com/community/noarch/cassandra12-1.2.9-1.noarch.rpm
RUN wget -N -q -P /home/REPLACE_USERNAME http://rpm.datastax.com/community/noarch/cassandra21-2.1.2-1.noarch.rpm
RUN rpm -i /home/REPLACE_USERNAME/cassandra*.rpm
# cassandra-install-man

# cassandra-tools-install-man
#RUN wget -N -q -P /home/REPLACE_USERNAME http://rpm.datastax.com/community/noarch/cassandra12-tools-1.2.9-1.noarch.rpm
RUN wget -N -q -P /home/REPLACE_USERNAME http://rpm.datastax.com/community/noarch/cassandra21-tools-2.1.2-1.noarch.rpm
RUN rpm -i /home/REPLACE_USERNAME/cassandra*-tools*.rpm
# service_stop_disable cassandra
# cassandra-tools-install-man

# mongo-install-pm
RUN yum install -y mongodb mongodb-server
RUN sed -i "s/.*bind_ip.*/bind_ip=0.0.0.0/" /etc/mongod.conf
# service_stop_disable mongod
# mongo-install-pm

# redis-install-pm
RUN yum install -y redis
RUN sed -i "s/.*bind.*/bind 0.0.0.0/" /etc/redis.conf
# service_stop_disable redis
# redis-install-pm

# ycsb-install-man
#RUN wget -N -q -P /home/REPLACE_USERNAME https://github.com/brianfrankcooper/YCSB/releases/download/0.4.0/ycsb-0.4.0.tar.gz
RUN wget -N -q -P /home/REPLACE_USERNAME https://github.com/brianfrankcooper/YCSB/releases/download/0.5.0/ycsb-0.5.0.tar.gz
RUN cd /home/REPLACE_USERNAME; tar -xvzf ycsb-*.tar.gz; sudo rm ycsb*.gz; sudo mv ycsb-* YCSB
# ycsb-install-man
RUN chown -R REPLACE_USERNAME:REPLACE_USERNAME /home/REPLACE_USERNAME