FROM REPLACE_NULLWORKLOAD_UBUNTU

# redis-install-pip
RUN pip install redis==2.10.6
# redis-install-pip

# mysql-install-pm
RUN echo "mysql-server-5.7 mysql-server/root_password password temp4now" | sudo debconf-set-selections; echo "mysql-server-5.7 mysql-server/root_password_again password temp4now" | sudo debconf-set-selections
RUN apt-get update
RUN apt-get install -y mysql-server python-mysqldb python-pip python-dev libmysqlclient-dev
# mysql-install-pm

# sysbench-install-pm
RUN apt-get install -y lsb-release
RUN lsb_release -sc
RUN wget https://repo.percona.com/apt/percona-release_latest.$(lsb_release -sc)_all.deb
RUN sudo dpkg -i percona-release_latest.$(lsb_release -sc)_all.deb
RUN apt-get update
RUN apt-get install -y sysbench sysbench-tpcc
# sysbench-install-pm

RUN chown -R REPLACE_USERNAME:REPLACE_USERNAME /home/REPLACE_USERNAME
