FROM REPLACE_NULLWORKLOAD_UBUNTU

# coremark-install-man
RUN apt-get update
RUN mkdir -p /home/REPLACE_USERNAME/3rd_party; chown -R REPLACE_USERNAME:REPLACE_USERNAME /home/REPLACE_USERNAME/3rd_party/
RUN REPLACE_RSYNC/coremark_v1.0.tar /home/REPLACE_USERNAME/3rd_party/
RUN cd /home/REPLACE_USERNAME/3rd_party/; tar -xf coremark_v1.0.tar; rm coremark_v1.0.tar; mv coremark_v1.0 _coremark-1.0
# coremark-install-man

RUN chown -R REPLACE_USERNAME:REPLACE_USERNAME /home/REPLACE_USERNAME