FROM REPLACE_NULLWORKLOAD_UBUNTU

RUN REPLACE_RSYNC/cuda-repo-ubuntu1604-8-0-local_8.0.44-1_amd64-deb /home/cbuser/
RUN dpkg -i /home/cbuser/cuda-repo-ubuntu1604-8-0-local_8.0.44-1_amd64-deb
RUN apt-get update
RUN sudo apt-get install -y cuda
#RUN cd /usr/local/cuda/samples/1_Utilities/deviceQuery; make
RUN REPLACE_RSYNC/pb2.5driver.tar /home/cbuser/
RUN REPLACE_RSYNC/pb2.5datasets_standard-2.tgz /home/cbuser/
RUN REPLACE_RSYNC/pb2.5benchmarks-2.tgz /home/cbuser/
RUN cd /home/cbuser; tar -xf pb2.5driver.tar
RUN cd /home/cbuser; tar -xf pb2.5benchmarks-2.tgz; mv benchmarks /home/cbuser/parboil
RUN cd /home/cbuser; tar -xf pb2.5datasets_standard-2.tgz; mv datasets /home/cbuser/parboil
RUN cd /home/cbuser/parboil; chmod u+x ./parboil; chmod u+x benchmarks/*/tools/compare-output
RUN chown -R cbuser:cbuser /home/cbuser