FROM REPLACE_NULLWORKLOAD_UBUNTU

# parboil-install-man
RUN REPLACE_RSYNC/cuda-repo-ubuntu1604-8-0-local_8.0.44-1_amd64-deb /home/REPLACE_USERNAME/
RUN dpkg -i /home/REPLACE_USERNAME/cuda-repo-ubuntu1604-8-0-local_8.0.44-1_amd64-deb
RUN apt-get update
RUN sudo apt-get install -y cuda
#RUN cd /usr/local/cuda/samples/1_Utilities/deviceQuery; make
RUN REPLACE_RSYNC/pb2.5driver.tar /home/REPLACE_USERNAME/
RUN REPLACE_RSYNC/pb2.5datasets_standard-2.tgz /home/REPLACE_USERNAME/
RUN REPLACE_RSYNC/pb2.5benchmarks-2.tgz /home/REPLACE_USERNAME/
RUN cd /home/REPLACE_USERNAME; tar -xf pb2.5driver.tar
RUN cd /home/REPLACE_USERNAME; tar -xf pb2.5benchmarks-2.tgz; mv benchmarks /home/REPLACE_USERNAME/parboil
RUN cd /home/REPLACE_USERNAME; tar -xf pb2.5datasets_standard-2.tgz; mv datasets /home/REPLACE_USERNAME/parboil
RUN cd /home/REPLACE_USERNAME/parboil; chmod u+x ./parboil; chmod u+x benchmarks/*/tools/compare-output
# parboil-install-man

RUN chown -R REPLACE_USERNAME:REPLACE_USERNAME /home/REPLACE_USERNAME