FROM REPLACE_NULLWORKLOAD_UBUNTU

RUN apt-get update

# apache-install-pm
RUN apt-get install -y apache2
# apache-install-pm

# wrk-install-man
RUN git clone https://github.com/wg/wrk.git; cd /home/REPLACE_USERNAME/wrk; make all
# wrk-install-man

RUN chown -R REPLACE_USERNAME:REPLACE_USERNAME /home/REPLACE_USERNAME
