FROM REPLACE_NULLWORKLOAD_UBUNTU

RUN apt-get update
# nuttcp-install-man
#RUN apt-get install -y nuttcp
RUN wget -N -q -P /home/REPLACE_USERNAME http://nuttcp.net/nuttcp/nuttcp-7.3.3/nuttcp-7.3.3.REPLACE_ARCH1
RUN mv /home/REPLACE_USERNAME/nuttcp* /usr/local/bin/nuttcp
RUN chmod 755 /usr/local/bin/nuttcp
# nuttcp-install-man
RUN chown -R REPLACE_USERNAME:REPLACE_USERNAME /home/REPLACE_USERNAME
