FROM REPLACE_NULLWORKLOAD_UBUNTU

RUN apt-get update
RUN apt-get install -y libaio1
RUN wget -N -P /home/cbuser https://sourceforge.net/projects/btest/files/Version-161/Linux_bin_x86-64/btest/download
RUN mv /home/cbuser/download /usr/local/bin/btest
RUN chmod 755 /usr/local/bin/btest
RUN cp /usr/local/bin/btest /home/cbuser/cbtool/3rd_party/btest