FROM REPLACE_BASE_VANILLA_UBUNTU

ENV DEBIAN_FRONTEND=noninteractive

USER root

RUN apt-get update; \
apt-get install -y vim sudo; \
useradd -ms /bin/bash REPLACE_USERNAME; \
echo "REPLACE_USERNAME  ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers

# sudo-install-man
RUN apt-get install -y sudo
# echo "USERNAME  ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers; sed -i s/"Defaults requiretty"/"#Defaults requiretty"/g /etc/sudoers
# sudo-install-man

# ifconfig-install-sl
RUN apt-get update; apt-get install -y net-tools; sudo ln -sf /sbin/ifconfig /usr/local/bin/ifconfig
# ifconfig-install-sl

# ip-install-sl
RUN sudo ln -sf /sbin/ip /usr/local/bin/ip
# ip-install-sl

# pkill-install-pm
RUN apt-get install -y psmisc coreutils
# pkill-install-pm

# which-install-pm
RUN /bin/true
# which-install-pm

# ntp-install-pm
RUN apt-get install -y ntp ntpdate
# ntp-install-pm

# git-install-pm
RUN apt-get install -y git bc
# git-install-pm

# wget-install-pm
RUN apt-get install -y wget
# wget-install-pm

# pip-install-pm
RUN apt-get update; apt-get install -y python3-pip
# pip-install-pm

# gcc-install-pm
RUN apt-get install -y gcc
# gcc-install-pm

# make-install-pm
RUN apt-get install -y make
# make-install-pm

# bc-install-pm
RUN apt-get install -y bc
# bc-install-pm

# sshpass-install-pm
RUN apt-get install -y sshpass
# sshpass-install-pm

# curl-install-pm
RUN apt-get install -y curl
# curl-install-pm

# screen-install-pm
RUN apt-get install -y screen
# screen-install-pm

# rsync-install-pm
RUN apt-get install -y rsync
# rsync-install-pm

# ncftp-install-pm
RUN apt-get install -y ncftp
# ncftp-install-pm

# lftp-install-pm
RUN apt-get install -y lftp iputils-ping
# lftp-install-pm

# haproxy-install-pm
RUN apt-get install -y haproxy
# service_stop_disable haproxy
# haproxy-install-pm

# netcat-install-man
RUN apt-get install -y netcat-openbsd
RUN cp /bin/nc /usr/local/bin/netcat
# netcat-install-man

# nmap-install-pm
RUN apt-get install -y nmap
# nmap-install-pm

# openvpn-install-pm
RUN apt-get install -y openvpn; sudo ln -sf /usr/sbin/openvpn /usr/local/bin/openvpn
# openvpn-install-pm

# gmond-install-pm
RUN apt-get install -y ganglia-monitor; sudo ln -sf /usr/sbin/gmond /usr/local/bin/gmond
# service_stop_disable ganglia-monitor
# gmond-install-pm

# rsyslog-install-pm
RUN apt-get install -y rsyslog; sudo ln -sf /usr/sbin/rsyslogd /usr/local/bin/rsyslogd; sudo mkdir -p /var/log/cloudbench
# rsyslog-install-pm

# rsyslog-filter-pm
RUN mkdir -p /var/log/cloudbench; sed -i -e "s/#\$ModLoad imudp/\$ModLoad imudp/g" /etc/rsyslog.conf; sed -i -e 's^#module(load="imudp")^module(load="imudp")^g' /etc/rsyslog.conf; sed -i  "s/#\$UDPServerRun.*/\$UDPServerRun $METRIC_STORE_PORT/g" /etc/rsyslog.conf
RUN bash -c "echo -e \"local5.*  \t\t\t\t /var/log/cloudbench/remote.log\" >> /etc/rsyslog.conf"; bash -c "echo -e \"local6.* \t\t\t\t /var/log/cloudbench/local.log\" >> /etc/rsyslog.conf"
#service_restart_enable rsyslog
# rsyslog-filter-pm

# apache-install-pm
RUN apt-get install -y apache2
# apache-install-pm

# redis-install-pm
RUN apt-get install -y redis-server; sed -i "s/.*bind 127.0.0.1/bind 0.0.0.0/" /etc/redis/redis.conf
# redis-install-pm
RUN sed -i "s/.*port.*/port $OBJECTSTORE_PORT/" /etc/redis/redis.conf

# mongodb-install-pm
RUN apt-get install -y mongodb; sed -i "s/.*bind_ip.*/bind_ip=0.0.0.0/" /etc/mongodb.conf
# mongodb-install-pm
RUN sed -i "s/.*port.*/port = $METRICSTORE_PORT/" /etc/mongodb.conf

# mysql-server-install-pm
RUN apt-get install -y mysql-server
# mysql-server-install-pm

# python-mysql-connector-install-pip
RUN pip3 install --upgrade mysql-connector
# python-mysql-connector-install-pip

# pylibvirt-install-pm
RUN apt-get install -y python3-libvirt
# pylibvirt-install-pm

# pypureomapi-install-pip
RUN pip3 install --upgrade pypureomapi
# pypureomapi-install-pip

# python3-devel-install-pm
RUN apt-get install -y python3-dev libffi-dev libssl-dev python3-libxml2 libxml2-dev libxslt1-dev libjpeg8-dev zlib1g-dev
# python3-devel-install-pm

# python-prettytable-install-pip
RUN pip3 install --upgrade prettytable docutils
# python-prettytable-install-pip

# python-daemon-install-pip
RUN pip3 install --upgrade python-daemon-3K
# python-daemon-install-pip

# python-twisted-install-pip
RUN pip3 install --upgrade twisted service_identity
# python-twisted-install-pip

# python-beaker-install-pip
RUN pip3 install --upgrade beaker
# python-beaker-install-pip

# python-webob-install-pip
RUN pip3 install --upgrade webob
# python-webob-install-pip

# pyredis-install-pip
RUN pip3 install redis
# pyredis-install-pip

# pymongo-install-pip
RUN pip3 install --upgrade mongo
# pymongo-install-pip

# pssh-install-pm
RUN apt-get install -y pssh
RUN ln -sf /usr/bin/parallel-ssh /usr/local/bin/pssh
# pssh-install-pm

# docutils-install-pip
RUN pip3 install --upgrade docutils
# docutils-install-pip

# python-setuptools-install-pip
RUN pip3 install --upgrade setuptools
# python-setuptools-install-pip

# markup-install-pip
RUN pip3 install --upgrade markup
# markup-install-pip

# pyyaml-install-pip
RUN pip3 install --upgrade pyyaml
# pyyaml-install-pip

# ruamelyaml-install-pip
RUN pip3 install --upgrade ruamel.yaml
# ruamelyaml-install-pip

# urllib3-install-pip
RUN pip3 install --upgrade  urllib3[secure]
# urllib3-install-pip

# jq-install-pm
RUN apt-get install -y jq
# jq-install-pm

# httplib2shim-install-pip
RUN pip3 install --upgrade httplib2shim
# httplib2shim-install-pip

# iptables-install-pm
RUN apt-get install -y iptables
# service_stop_disable iptables
# iptables-install-pm

# sshd-install-pm
RUN apt-get install -y openssh-server; sudo bash -c "echo 'UseDNS no' >> /etc/ssh/sshd_config"; sed -i 's/.*UseDNS.*/UseDNS no/g' /etc/ssh/sshd_config; sed -i 's/.*GSSAPIAuthentication.*/GSSAPIAuthentication no/g' /etc/ssh/sshd_config
# sshd-install-pm

# novaclient-install-pip
RUN pip3 install --upgrade pbr
RUN pip3 install --upgrade netifaces
RUN pip3 install --upgrade python-novaclient==9.1.1
# novaclient-install-pip

# neutronclient-install-pip
RUN pip3 install --upgrade python-neutronclient==6.5.0
# neutronclient-install-pip

# cinderclient-install-pip
RUN pip3 install --upgrade python-cinderclient==3.2.0
# cinderclient-install-pip

# glanceclient-install-pip
RUN pip3 install --upgrade python-glanceclient==2.8.0
# glanceclient-install-pip

# softlayer-install-pip
RUN pip3 install --upgrade softlayer
# softlayer-install-pip

# boto-install-pip
RUN pip3 install --upgrade boto
# boto-install-pip

# libcloud-install-pip
RUN pip3 install --upgrade apache-libcloud
# libcloud-install-pip

# pygce-install-pip
RUN pip3 install --upgrade gcloud google-api-python-client
# pygce-install-pip

# docker-install-pip
RUN pip3 install --upgrade docker wget
# docker-install-pip

# pylxd-install-pip
RUN pip3 install --upgrade pylxd
# pylxd-install-pip

# pykube-ng-install-pip
RUN pip3 install --upgrade pykube-ng
# pykube-ng-install-pip

# R-install-pm
RUN apt-get install -y r-base-core
# R-install-pm

# rrdtool-install-pm
RUN apt-get install -y rrdtool
# rrdtool-install-pm

# python-rrdtool-install-pm
RUN apt-get install -y python3-rrdtool
# python-rrdtool-install-pm

# python-dateutil-install-pip
RUN pip3 install --upgrade python-dateutil
# python-dateutil-install-pip

# python-pillow-install-pip
RUN pip3 install --upgrade Pillow
# python-pillow-install-pip

# python-jsonschema-install-pip
RUN pip3 install --upgrade jsonschema
# python-jsonschema-install-pip

USER REPLACE_USERNAME
# gcloud-install-man
ENV CLOUDSDK_CORE_DISABLE_PROMPTS=1
RUN bash -c "export CLOUDSDK_CORE_DISABLE_PROMPTS=1; if [[ $(uname -p) != "ppc64le" ]]; then curl https://sdk.cloud.google.com | bash; else /bin/true; fi"
RUN bash -c "if [[ $(uname -p) != "ppc64le" ]]; then sudo ln -sf /home/REPLACE_USERNAME/google-cloud-sdk/bin/gcloud /usr/local/bin/gcloud; else /bin/true; fi"
RUN sudo ln -sf /home/REPLACE_USERNAME/google-cloud-sdk/bin/gcloud /usr/local/bin/gcloud
# gcloud-install-man

WORKDIR /home/REPLACE_USERNAME/

# gmetad-python-install-git
RUN mkdir -p /home/REPLACE_USERNAME/cbtool/3rd_party/workload; \
cp____-f____/home/REPLACE_USERNAME/cbtool/util/manually_download_files.txt____/home/REPLACE_USERNAME/cbtool/3rd_party/workload; /bin/true
WORKDIR /home/REPLACE_USERNAME/cbtool/3rd_party
RUN git clone https://github.com/ibmcb/monitor-core.git
# gmetad-python-install-git

# pyhtml-install-git
WORKDIR /home/REPLACE_USERNAME/cbtool/3rd_party
RUN sudo rm -rf HTML.py; git clone https://github.com/ibmcb/HTML.py.git; cd HTML.py; sudo python3 setup.py install
# pyhtml-install-git

# bootstrap-install-git
WORKDIR /home/REPLACE_USERNAME/cbtool/3rd_party
RUN git clone https://github.com/ibmcb/bootstrap.git
# bootstrap-install-git

# bootstrap-wizard-install-git
WORKDIR /home/REPLACE_USERNAME/cbtool/3rd_party
RUN git clone https://github.com/ibmcb/Bootstrap-Wizard.git
# bootstrap-wizard-install-git

# streamprox-install-git
WORKDIR /home/REPLACE_USERNAME/cbtool/3rd_party
RUN git clone https://github.com/ibmcb/StreamProx.git
# streamprox-install-git

# d3-install-git
WORKDIR /home/REPLACE_USERNAME/cbtool/3rd_party
RUN git clone https://github.com/ibmcb/d3.git
# d3-install-git

ADD installrlibs.R /usr/local/bin/installrlibs
RUN sudo chmod +x /usr/local/bin/installrlibs; sudo /usr/local/bin/installrlibs

USER root
RUN ssh-keygen -q -t rsa -N '' -f /root/.ssh/id_rsa; \
touch /root/.ssh/authorized_keys; \
chmod 644 /root/.ssh/authorized_keys; \
mkdir -p /home/REPLACE_USERNAME/.ssh/; \
echo "StrictHostKeyChecking no" > /root/.ssh/config; \
echo "UserKnownHostsFile=/dev/null" >> /root/.ssh/config; \
echo "HashKnownHosts no" >> /root/.ssh/config; \
rsync -a /root/.ssh/ /home/REPLACE_USERNAME/.ssh/; \
mkdir /home/REPLACE_USERNAME/repos; \
chown -R REPLACE_USERNAME:REPLACE_USERNAME /home/REPLACE_USERNAME/;

#
#

ARG CLOUDBENCH_VERSION=AUTO

#
#
#
#
#
#
#

ADD get_my_ips.sh /usr/local/bin/getmyips
ADD gucn.sh /usr/local/bin/gucn

WORKDIR /home/REPLACE_USERNAME/
RUN git clone https://github.com/ibmcb/cbtool.git cbtooltmp; \
cd /home/REPLACE_USERNAME/cbtooltmp; git checkout REPLACE_BRANCH; \
rsync -a /home/REPLACE_USERNAME/cbtooltmp/ /home/REPLACE_USERNAME/cbtool; \
rm -rf /home/REPLACE_USERNAME/cbtooltmp/; \
cp -f /home/REPLACE_USERNAME/cbtool/util/manually_download_files.txt /home/REPLACE_USERNAME/cbtool/3rd_party/workload; \
cd /home/REPLACE_USERNAME/cbtool; \
mv configs private_configs; \
mkdir configs; \
mkdir -p data; \
mv data private_data; \
mkdir data; \
chmod +x /usr/local/bin/getmyips; \
chmod +x /usr/local/bin/gucn;

#

#
#
#

#
#
#
#
#
#

RUN chown -R REPLACE_USERNAME:REPLACE_USERNAME /home/REPLACE_USERNAME/

USER REPLACE_USERNAME

#

WORKDIR /home/REPLACE_USERNAME/cbtool
