FROM REPLACE_PREREQS_UBUNTU

WORKDIR /home/REPLACE_USERNAME/
RUN git clone https://github.com/ibmcb/cbtool.git; cd /home/REPLACE_USERNAME/cbtool; git checkout REPLACE_BRANCH
RUN cd /home/REPLACE_USERNAME/cbtooltmp/; mv 3rd_party ../cbtool/
RUN cp -f /home/REPLACE_USERNAME/cbtool/util/manually_download_files.txt /home/REPLACE_USERNAME/cbtool/3rd_party/workload
RUN cd /home/REPLACE_USERNAME/cbtool; mv configs private_configs
#; mv data private_data

WORKDIR /home/REPLACE_USERNAME/cbtool